const USER_ROLES = {
  USER: 'USER',
  ADMIN: 'ADMIN',
};

const USER_STATUS = {
  PENDING_VERIFICATION: 'PENDING_VERIFICATION',
  ACTIVE: 'ACTIVE',
  BLOCKED: 'BLOCKED',
};

const PRODUCT_TYPE = {
  ELECTRONICS : "ELECTRONICS",
  CLOTHING : "CLOTHING",
  FURNITURE : "FURNITURE",
  HEALTH : "HEALTH",
  BEAUTY : "BEAUTY",
  BOOKS : "BOOKS",
  TOYS_AND_GAMES : "TOYS_AND_GAMES",
  ART_AND_CRAFT : "ART_AND_CRAFT",
  OTHERS:'OTHERS'
}

module.exports = {
  USER_ROLES,
  USER_STATUS,
  PRODUCT_TYPE
};
